=== SalazarMalagon/SalazarMalagon/Generador-de-APIs-main/Proyecto/api_generador_projecto/schemas/modelorelacional.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="DiagramaE_R">
        <xs:complexType>
            
            <xs:sequence>
                <xs:element name="Nombre" type="xs:string"/>
                <!-- Estructura de las entidades -->
                <xs:element name="Entidad" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombreEntidad" />
                            <xs:sequence>
                                <!-- Estructura de cada atributo -->
                                <xs:element name="Atributo"
                                    maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="tipo_dato" type="xs:string" />
                                            <xs:element name="nombre" type="xs:string" />
                                            <xs:element name="llavePrimaria"
                                                type="xs:boolean" minOccurs="0"
                                                maxOccurs="unbounded" />
                                            <xs:element name="autoincrementable" type="xs:boolean" minOccurs="0"/>
                                            <xs:element name="llaveForanea"
                                                type="xs:boolean" minOccurs="0"
                                                maxOccurs="unbounded" />
                                            <xs:element name="llaveUnica" type="xs:boolean"
                                                minOccurs="0" maxOccurs="unbounded" />
                                            <xs:element name="nullable" type="xs:boolean"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Estructura de las relaciones -->
                <xs:element name="Relaciones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Relacion" minOccurs="0"
                                maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="EntidadPrincipal" type="xs:string" />
                                        <xs:element name="EntidadDependiente" type="xs:string" />
                                        <xs:choice>
                                            <xs:element name="RelacionUnoAMuchos"
                                                type="xs:string" />
                                            <xs:element name="RelacionUnoAUno"
                                                type="xs:string" />
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>


            </xs:sequence>
        </xs:complexType>


    </xs:element>

</xs:schema>

=== SalazarMalagon/SalazarMalagon/Generador-de-APIs-main/Prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<DiagramaE_R xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="modelorelacional.xsd">
    <Nombre>Prueba</Nombre>
    <Entidad>
        <nombreEntidad>Clientes</nombreEntidad>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>cod_cliente</nombre>
            <llavePrimaria>true</llavePrimaria>
            <autoincrementable>true</autoincrementable>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>dni</nombre>
            <llaveUnica>true</llaveUnica>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>nombre</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>apellido1</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>apellido2</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>direccion</nombre>
            <nullable>true</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>email</nombre>
            <llaveUnica>true</llaveUnica>
            <nullable>false</nullable>
        </Atributo>
    </Entidad>
    <Entidad>
        <nombreEntidad>Prestamos</nombreEntidad>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>id_prestamo</nombre>
            <llavePrimaria>true</llavePrimaria>
            <autoincrementable>true</autoincrementable>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>TIME</tipo_dato>
            <nombre>fecha_pretamo</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>TIME</tipo_dato>
            <nombre>fecha_tope</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>TIME</tipo_dato>
            <nombre>fecha_entrega</nombre>
            <nullable>true</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>cod_cliente</nombre>
            <llaveForanea>true</llaveForanea>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>n_copia</nombre>
            <llaveForanea>true</llaveForanea>
            <nullable>false</nullable>
        </Atributo>
    </Entidad>
    <Entidad>
        <nombreEntidad>Copias</nombreEntidad>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>n_copia</nombre>
            <llavePrimaria>true</llavePrimaria>
            <autoincrementable>true</autoincrementable>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>BOOLEAN</tipo_dato>
            <nombre>deteriorada</nombre>
            <nullable>true</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>formato</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>id_pelicula</nombre>
            <llaveForanea>true</llaveForanea>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>precio_alquiler</nombre>
            <nullable>true</nullable>
        </Atributo>
    </Entidad>
    <Entidad>
        <nombreEntidad>Peliculas</nombreEntidad>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>id_pelicula</nombre>
            <llavePrimaria>true</llavePrimaria>
            <autoincrementable>true</autoincrementable>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>titulo</nombre>
            <nullable>false</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>INT</tipo_dato>
            <nombre>a√±o</nombre>
            <nullable>true</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>critica</nombre>
            <nullable>true</nullable>
        </Atributo>
        <Atributo>
            <tipo_dato>VARCHAR</tipo_dato>
            <nombre>caratula</nombre>
            <nullable>true</nullable>
        </Atributo>
    </Entidad>
    <Relaciones>
        <Relacion>
            <EntidadPrincipal>Clientes</EntidadPrincipal>
            <EntidadDependiente>Prestamos</EntidadDependiente>
            <RelacionUnoAMuchos>Uno a Muchos</RelacionUnoAMuchos>
        </Relacion>
        <Relacion>
            <EntidadPrincipal>Copias</EntidadPrincipal>
            <EntidadDependiente>Prestamos</EntidadDependiente>
            <RelacionUnoAUno>Uno a Muchos</RelacionUnoAUno>
        </Relacion>
        <Relacion>
            <EntidadPrincipal>Peliculas</EntidadPrincipal>
            <EntidadDependiente>Copias</EntidadDependiente>
            <RelacionUnoAUno>Uno a Muchos</RelacionUnoAUno>
        </Relacion>
    </Relaciones>
</DiagramaE_R>
